Repository thkrp/homepage, pull requests merged in 2021-01, with the labels that each got.

#3 First release to production
  index.html
Labels: release

#9 add base.css stylesheet and meta tags
  index.html
Labels: enhancement

#15 add primary content
  index.html
Labels: enhancement

#16 add secondary information
  index.html
Labels: enhancement

#17 add fixes and styles
  README.md
  assets/css/custom.css
  index.html
Labels: enhancement

#18 add content
  README.md
  assets/css/custom.css
  index.html
Labels: enhancement

#19 Release to production
  README.md
  assets/css/custom.css
  index.html
Labels: release

#21 fix icon tags and lang
  index.html
Labels: bug

#22 update production
  index.html
Labels: release

#23 add workbox config
  sw.js
  sw.js.map
  workbox-53ba01ab.js
  workbox-53ba01ab.js.map
  workbox-config.js
Labels: enhancement

#24 to production
  .gitignore
  sw.js
  sw.js.map
  workbox-53ba01ab.js
  workbox-53ba01ab.js.map
  workbox-config.js
Labels: release

#26 fix style validation
  assets/css/custom.css
Labels: bug

#28 First release to production
  assets/css/custom.css
  sw.js
  sw.js.map
Labels: release

#29 Create now.json
  now.json
Labels: enhancement

#30 fixe style validation
  assets/css/custom.css
Labels: bug

#31 release to production
  .gitignore
  assets/css/custom.css
  now.json
  sw.js
  sw.js.map
Labels: release
